typography_spectrum: 0.82834452833049
color:
  brandStrength: 0.057531445287168026
  lightness: 0.41509936726652086
  saturation: 0.9954776959493756
  rhythmicContrast: 0.4047477215062827
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.40770113724283874
name: Kitethrills Mauritius
navigation:
  - name: Mauritius website
    url: 'http://kitethrills.com/mauritius'
    type: external
title: Kitesurf Mauritius
description: Easy fun in the worlds best location
